### ISSUE TITLE
Install add sftp/ftp failing on eXR

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#11]
The problem is that CSMPE does not receive the expected string  “Mar 11 13:55:21 Install operation will continue in the background” from the following context:
 
RP/0/RSP0/CPU0:vkg3#install add source sftp://administrator@172.27.148.198//tftpboot/csm/eXRasr9k-k9sec-x64-2.1.0.0-r6399.x86_64.rpm
 
Mar 11 13:55:04 Install operation 70 started by root:
install add source sftp://administrator@172.27.148.198//tftpboot/csm/eXR asr9k-k9sec-x64-2.1.0.0-r6399.x86_64.rpm
password:Mar 11 13:55:21 Install operation will continue in the background
 
By adding some debug print around the following code in condoor/device.py line 249:
 
def execute_command (self, cmd, timeout, wait_for_string):
 
            logger.info("output: '{}'".format(output))
            second_line_index = output.find('\n') + 1
            output = output[second_line_index:]
            logger.info("second_line_index: '{}'".format(second_line_index))
            logger.info("output: '{}'".format(output))
 
The output got filtered out here. If I remove the two lines that are highlight above, the problem is resolved.

**Comment by kstaniek** [comment]
@jamesjwei James, can you please make some additional testing for other platforms without those lines. It passes all the test cases but I'm afraid that this change may affect plugins for the other platforms.

**Comment by jamesjwei** [comment]
Will do! WIll cover all the different flavors of OS (cXR, eXR, NG-XR, IOS-XE, and IOS) and let you know.
