### ISSUE TITLE
xr reload fsm needs a little twisting for migration

### ISSUE THREAD

**Issue by joydai** [kstaniek/condoor#12]
With new trial of migration on ASR9K classic XR, when eXR boots up, the "Username:" prompt is seen after seeing "Press RETURN to get started." We don't see prompts like configuration in progress/completed or reconfigure username/password before that.

In this use case, if I'm understanding the condoor log correctly, it seems that the starting states for the username prompt should also include 6 and 7 because the reload FSM gets to state 6 after seeing "Press RETURN to get started.", after which we see the username prompt. 

Logs are sent through email.

**Comment by kstaniek** [comment]
@joydai Could you make a pull request with the proposed changes, please?

**Comment by joydai** [comment]
@kstaniek Sure. Right now we are having some other problems with the testing device, I will send a pull request when ready.

**Comment by joydai** [comment]
@kstaniek here is the pull request #15 

It is a little different from the proposed change above after considering the case of regular XR reload also.
