### ISSUE TITLE
Inconsistency between condoor.log and session.log

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#14]
On csmpe-lnx.cisco.com:5000, look into the logs at 2017-03-18 08:26:56 that condoor.log shows that it had issued a lot of commands and received quite a few responses from the host, but the session.log only has three lines. It looks like part of the transactions are missing from session.log.

**Comment by kstaniek** [comment]
@jamesjwei I can't find those logs on the server, could you please email it to me directly?

**Comment by kstaniek** [comment]
@jamesjwei I think this is fine. The condoor.log contains all the activities done by connection class, between multiple connect and disconnect methods for the whole object life. The session log keeps the interaction with the device details (session) between single connect and disconnect.
That is fine for me and it's not a reason to worry.
