### ISSUE TITLE
Add telnet connect FSM for XE when no password is required

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#2]
The Finite State Machine (FSM) in the connection module is not able to handle ‘no login’ configuration under line vty.

line vty 0 4
exec-timeout 0 0
password lab
no login

**Comment by kstaniek** [comment]
@jamesjwei, please email me the DUT credentials.

**Comment by kstaniek** [comment]
@jamesjwei I can't reproduce it. It works with latest condoor.
