### ISSUE TITLE
ssh window row_size incompatible with IOS-XR implementation

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor#37]
The following error message is seen on console and the ssh connection is done via the management interface. 

RP/0/RSP0/CPU0:EPN-PE3#RP/0/RSP0/CPU0:May  3 06:46:21.413 : SSHD_[65812]: %SECURITY-SSHD-3-ERR_ERRNO : Failed to set window size: %s 'tty-infra' detected the 'fatal' condition 'An invalid operation has been requested' 

see: http://cdetsweb-prd.cisco.com/apps/dumpcr?identifier=CSCvd81680&parentprogram=QDDTS
it is the term width (from vty) that is causing us trouble here.

in the ssh tty setup from the client side/csm are we setting rows >512? that would trigger this issue.

**Comment by kstaniek** [comment]
Fixed in 1.0.0
