### ISSUE TITLE
Support both NCS1001 and NCS1002

### ISSUE THREAD

**Issue by csm-aut** [kstaniek/condoor#45]
Currently, condoor classifies both NCS1001 and NCS1002 as NCS1K family.  It is proposed that they being classified as

Device        Family
NCS1001    NCS1001
NCS1002    NCS1K

This device can be used to test the code. But, please do not change anything.

10.89.195.241 (root/lab)

**Comment by kstaniek** [comment]
@csm-aut Please let me know if this works as expected.
