### ISSUE TITLE
fails to capture platform string for CRS device

### ISSUE THREAD

**Issue by joydai** [kstaniek/condoor#6]
For a CRS device I was working with, the platform should be captured as "CRS-16/S-B", but instead we got none.
From a glimpse, it looks like the pid2platform regex: '([A-Z]{3}[-| ]?[0-9]{3,4})' cannot capture platform for CRS.
I will email you the telnet info for that CRS device.

**Comment by kstaniek** [comment]
Potentially '([A-Z]{3}[-| ]?[0-9]{2,4})' should solve the issue.
