### ISSUE TITLE
dynamic prompt in jump server not expected

### ISSUE THREAD

**Issue by joydai** [kstaniek/condoor#7]
I run into a corner case where the jump server's prompt updates the numbering in itself after a command is issued, like below we have a jump server "sj16lab-as1":
sj16lab-as1:129>
sj16lab-as1:129>
sj16lab-as1:129> uname -sr
Linux 2.6.32-642.11.1.el6.x86_64
sj16lab-as1:130>

After ssh into it, condoor issues "uname -sr" and waits for "sj16lab-as1:129>" as prompt, but actually we get "sj16lab-as1:130>".(The number increments by 1 whenever a command is issued.)

In this case, condoor throws CommandTimeoutError and fails the job.

Logs for this issue and issue #6 will be sent through email.

**Comment by kstaniek** [comment]
That would be a tricky to fix. I would rather check if the prompt can be changed for the jumphost user.
